// Zip a converted bundle for download.
import JSZip from "jszip";
import type { ConvertedFile } from "./types";

export async function zipBundle(files: ConvertedFile[]): Promise<Buffer> {
  const zip = new JSZip();
  for (const f of files) {
    const path = f.path.replace(/^\/+/, "");
    if (f.binary) zip.file(path, f.binary);
    else zip.file(path, f.content ?? "");
  }
  // A tiny readme so the download is self-explanatory.
  zip.file(
    "_README.txt",
    "Optimized static site generated by Framer → Next.js Optimizer.\n" +
      "These are plain static .html files + /assets. Deploy the folder as-is to\n" +
      "any static host (Netlify drop, Vercel, Cloudflare Pages, GitHub Pages).\n" +
      "Do NOT run a build step — it is already built.\n"
  );
  return zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" });
}
